/*
 * %W% %E%
 *
 * Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */
package com.sun.org.omg.CORBA;


/**
* com/sun/org/omg/CORBA/IDLTypeOperations.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from ir.idl
* Thursday, May 6, 1999 1:51:45 AM PDT
*/

public interface IDLTypeOperations  extends com.sun.org.omg.CORBA.IRObjectOperations
{
    org.omg.CORBA.TypeCode type ();
} // interface IDLTypeOperations
